#!/usr/bin/env python3
"""Generate the synthetic multichannel NWB demo fixture.

This is a development tool, not runtime code. It requires PyNWB:

    python3 -m pip install pynwb
    python3 tools/make-nwb-fixture.py

The generated signal is synthetic and intentionally labeled that way in the NWB
metadata. Do not present this fixture as a biological recording.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
from pynwb import NWBHDF5IO, NWBFile, TimeSeries


CHANNEL_COUNT = 24
DURATION_SECONDS = 6
SAMPLE_RATE_HZ = 1000.0
OUTPUT_PATH = Path("data/nwb-excerpt.nwb")
RNG_SEED = 20260602


def build_signal() -> np.ndarray:
    sample_count = int(DURATION_SECONDS * SAMPLE_RATE_HZ)
    time = np.arange(sample_count, dtype=np.float32) / SAMPLE_RATE_HZ
    rng = np.random.default_rng(RNG_SEED)
    data = np.zeros((sample_count, CHANNEL_COUNT), dtype=np.float32)

    for channel in range(CHANNEL_COUNT):
        frequency = 4.0 + (channel % 8) * 1.75
        amplitude = 12.0 + (channel % 6) * 3.0
        phase = channel * 0.37
        slow = 8.0 * np.sin(2 * np.pi * (0.35 + channel * 0.015) * time + phase / 2)
        carrier = amplitude * np.sin(2 * np.pi * frequency * time + phase)
        noise = rng.normal(0.0, 4.0 + channel * 0.08, sample_count)
        data[:, channel] = carrier + slow + noise

    burst_centers_seconds = [0.65, 1.35, 2.25, 3.1, 4.05, 5.1]
    burst_width_samples = int(0.022 * SAMPLE_RATE_HZ)
    kernel_t = np.linspace(-1.0, 1.0, burst_width_samples, dtype=np.float32)
    spike_kernel = -165.0 * np.exp(-(kernel_t * 4.2) ** 2)
    rebound_kernel = 54.0 * np.exp(-((kernel_t - 0.32) * 7.0) ** 2)
    burst_kernel = spike_kernel + rebound_kernel

    for burst_index, center_seconds in enumerate(burst_centers_seconds):
        center = int(center_seconds * SAMPLE_RATE_HZ)
        start = max(0, center - burst_width_samples // 2)
        end = min(sample_count, start + burst_width_samples)
        segment = burst_kernel[: end - start]
        first_channel = (burst_index * 4) % CHANNEL_COUNT
        active_channels = range(first_channel, min(first_channel + 8, CHANNEL_COUNT))
        for channel in active_channels:
            scale = 0.75 + (channel % 5) * 0.12
            data[start:end, channel] += segment * scale

    return data


def create_fixture(output_path: Path) -> None:
    data = build_signal()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    nwbfile = NWBFile(
        session_description=(
            "Synthetic multichannel ElectricalSeries demo excerpt for fs-kernel. "
            "This is not a biological recording."
        ),
        identifier="fs-kernel-synthetic-nwb-demo-20260602",
        session_start_time=datetime(2026, 6, 2, tzinfo=timezone.utc),
        experimenter=["Synthetic fixture generator"],
        lab="fs-kernel demo",
        institution="MikMikMiller/finalspark",
        keywords=["synthetic", "demo", "multichannel", "fs-kernel"],
    )

    series = TimeSeries(
        name="synthetic_multichannel_microvolts",
        data=data,
        starting_time=0.0,
        rate=SAMPLE_RATE_HZ,
        unit="microvolts",
        description=(
            "Synthetic 24-channel, 6-second signal with deterministic bursts for "
            "browser rendering verification."
        ),
        comments="Generated by tools/make-nwb-fixture.py; not a real recording.",
    )
    nwbfile.add_acquisition(series)

    with NWBHDF5IO(str(output_path), "w") as io:
        io.write(nwbfile)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args()
    create_fixture(args.output)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
